namespace Ida.Application.Features.Users;

public static class TenantPermissionCatalog
{
    public static IReadOnlyList<(string Name, string DisplayNameTh, string Module, bool IsGroupLevel)> Resources { get; } =
    [
        ("external-fee-lines", "รายการค่าแพทย์ภายนอก", "doctor-fee-402", false),
        ("external-fees", "ค่าแพทย์ภายนอก", "doctor-fee-402", false),
        ("fee-items", "รายการค่าแพทย์", "doctor-fee-402", false),
        ("hospital-paid-taxes", "ภาษีโรงพยาบาลออกให้", "doctor-fee-402", false),
        ("position-fees", "ค่าบริหาร / ตำแหน่ง", "doctor-fee-402", false),
        ("tax-deduction-items", "รายการลดหย่อน", "doctor-fee-402", false),
        ("tax-deductions", "ภาษีลดหย่อน", "doctor-fee-402", false),
        ("tax-exemptions", "ข้อมูลยกเว้นภาษี", "doctor-fee-402", false),
        ("bad-debt-tiers", "ขั้นบันไดหนี้สูญ", "doctor-fee-406", false),
        ("bu-doctor-documents", "เอกสารแพทย์ระดับโรงพยาบาล", "doctors", false),
        ("doctor-bank-accounts", "บัญชีธนาคารของแพทย์", "doctors", false),
        ("doctor-codes", "รหัสแพทย์", "doctors", false),
        ("doctor-contracts", "สัญญาแพทย์", "doctors", false),
        ("doctor-specialties", "ความเชี่ยวชาญของแพทย์", "doctors", false),
        ("doctor-welfares", "สวัสดิการแพทย์", "doctors", false),
        ("welfare-plans", "แผนสวัสดิการแพทย์", "doctors", false),
        ("duty-rate-days", "อัตราค่าเวรรายวัน", "duty-rates", false),
        ("duty-rates", "อัตราค่าแพทย์เวร", "duty-rates", false),
        ("guarantee-rate-days", "เงื่อนไขรายวันของประกันรายได้", "duty-rates", false),
        ("guarantee-rate-treatments", "Treatment ที่เทียบประกันรายได้", "duty-rates", false),
        ("guarantee-rates", "ประกันรายได้", "duty-rates", false),
        ("holiday-duty-exclusions", "รายการยกเว้นแพทย์ (วันหยุด)", "duty-rates", false),
        ("holiday-duty-rates", "อัตราค่าเวรวันหยุดเทศกาล", "duty-rates", false),
        ("duty-schedules", "ตารางเวร", "duty-schedules", false),
        ("duty-shift-doctors", "การลงเวลาแพทย์", "duty-schedules", false),
        ("duty-shifts", "เวร", "duty-schedules", false),
        ("slip-settings", "ตั้งค่าการออกสลิป", "income-documents", false),
        ("ar-codes", "AR Code", "master-data-accounting", false),
        ("gl-posting-setups", "ตั้งค่าบันทึกบัญชี", "master-data-accounting", false),
        ("income-deduction-items", "รายได้และรายการหัก", "master-data-accounting", false),
        ("no-wait-payment-rules", "รายการไม่รอรับชำระ", "master-data-accounting", false),
        ("payment-types", "ประเภทการจ่ายเงิน", "master-data-accounting", false),
        ("receipt-types", "ประเภทการรับเงิน", "master-data-accounting", false),
        ("share-categories", "ประเภทส่วนแบ่ง", "master-data-accounting", false),
        ("tax-types", "ประเภทภาษี", "master-data-accounting", false),
        ("treatment-categories", "Treatment Category", "master-data-accounting", false),
        ("treatments", "Treatment", "master-data-accounting", false),
        ("clinics", "คลินิก", "master-data-general", false),
        ("departments", "แผนก", "master-data-general", false),
        ("doctor-groups", "กลุ่มแพทย์", "master-data-general", false),
        ("doctor-types", "ประเภทแพทย์", "master-data-general", false),
        ("privilege-subtypes", "Privilege SubType", "master-data-general", false),
        ("privilege-types", "Privilege Type", "master-data-general", false),
        ("status-privileges", "Status Privilege", "master-data-general", false),
        ("adjustment-types", "ประเภทรายการปรับปรุง", "master-data-tax-402", false),
        ("expense-types", "ประเภทรายการค่าใช้จ่าย", "master-data-tax-402", false),
        ("income-types-402", "ประเภทเงินได้", "master-data-tax-402", false),
        ("invoice-ar-cash-rules", "Invoice AR/Cash", "master-data-tax-406", false),
        ("invoice-prefix-rules", "Import Invoice", "master-data-tax-406", false),
        ("patient-rights", "สิทธิ์คนไข้", "share-rates", false),
        ("share-rate-exclusions", "รายการยกเว้นแพทย์", "share-rates", false),
        ("share-rates", "ส่วนแบ่งค่าแพทย์", "share-rates", false),
        ("checkin-areas", "ตั้งค่าพื้นที่การลงชื่อเข้าเวร", "system-settings", false),
        ("expiry-alert-settings", "ตั้งค่าแจ้งเตือนรายการใกล้หมดอายุ", "system-settings", false),
        ("his-doctor-code-maps", "รหัสแพทย์ไปเป็นแพทย์กลาง", "system-settings", false),
        ("his-notify-emails", "อีเมล HIS", "system-settings", false),
        ("income-doc-settings", "ตั้งค่าการส่งเอกสารรายได้", "system-settings", false),
    ];
}
