apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bu02
resources:
  - namespace.yaml
  - ../../base/worker
  - ../../base/database
configMapGenerator:
  - name: worker-config
    behavior: merge
    literals:
      - Bu__Id=BU02
      - Bu__QueueName=jobs.bu02
  - name: database-config
    behavior: merge
    literals:
      - POSTGRES_DB=ida_bu02
      - APP_DB_USER=bu02user
