apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - client-service.yaml
  - statefulset.yaml
  - network-policy.yaml
configMapGenerator:
  - name: core-database-config
    literals:
      - POSTGRES_DB=ida_core
      - APP_DB_USER=core_app
  - name: core-database-init
    files:
      - init-database.sh
