apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: core-database-isolation
spec:
  podSelector:
    matchLabels:
      app: core-db
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: core-api
      ports:
        - protocol: TCP
          port: 5432
  egress: []
