<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>iDA.Bu.Worker</AssemblyName>
    <RootNamespace>iDA.Bu.Worker</RootNamespace>
    <UserSecretsId>dotnet-iDA.Bu.Worker-3c766bd7-3f4e-42d5-8ff8-94863ce47954</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Local.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
  </ItemGroup>
</Project>
