apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service-account.yaml
  - network-policy.yaml
configMapGenerator:
  - name: worker-config
    literals:
      - Core__BaseUrl=http://core-api.core.svc.cluster.local:3100
