apiVersion: v1
kind: Service
metadata:
  name: bu-db-client
spec:
  type: ClusterIP
  selector:
    app: bu-db
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
