apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - client-service.yaml
  - statefulset.yaml
  - network-policy.yaml
configMapGenerator:
  - name: database-config
    literals:
      - POSTGRES_DB=ida_bu
      - APP_DB_USER=bu_app
  - name: database-init
    files:
      - init-database.sh
