import type { IconName } from '../components/Icon';
export const GROUP_ICONS: Record<string, IconName> = {
    'หน้าหลัก': 'home',
    'Dashboard': 'chart',
    'คำขอและการอนุมัติ': 'clipboard',
    'ข้อมูลหลักทั่วไป': 'database',
    'ข้อมูลหลักทางบัญชี': 'banknote',
    'ข้อมูลหลัก 40(2)': 'percent',
    'ข้อมูลหลัก 40(6)': 'percent',
    'จัดการข้อมูลแพทย์': 'users',
    'ส่วนแบ่งค่าแพทย์ · Premium': 'layers',
    'ส่วนแบ่งค่าแพทย์ · ประกันสังคม': 'shield',
    'อัตราค่าเวรและประกันรายได้': 'clock',
    'ตารางเวรและการลงชื่อเข้าเวร': 'calendar',
    'จัดการค่าแพทย์ 40(2)': 'banknote',
    'จัดการค่าแพทย์ 40(6)': 'calculator',
    'การนำเข้าข้อมูล': 'database',
    'จัดการค่าแพทย์สิทธิ์ร่วม': 'shield',
    'การปรับปรุงรายการ': 'pencil',
    'คำนวณค่าแพทย์รายเดือน': 'calculator',
    'เอกสารรายได้': 'receipt',
    'สรรพากร': 'fileText',
    'จัดการผู้ใช้': 'users',
    'ตั้งค่าระบบ': 'settings',
};
