<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\iDA.Common\api\Ida.Common.Api.csproj" />
    <ProjectReference Include="..\infrastructure\Ida.Tenant.Infrastructure.csproj" />
    <Content Include="..\..\appsettings*.json" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Update="..\..\appsettings.local.json" CopyToPublishDirectory="Never" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>iDA.Tenant.Api</AssemblyName>
  </PropertyGroup>

</Project>
